<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Ecore" nsURI="http://www.eclipse.org/emf/2002/Ecore" nsPrefix="Ecore">
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeature" abstract="true" eSuperTypes="//ETypedElement">
    <eOperations name="getContainerClass">
      <eType xsi:type="ecore:EDataType" href="#//EJavaClass"/>
    </eOperations>
    <eOperations name="getFeatureID">
      <eType xsi:type="ecore:EDataType" href="#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainingClass" lowerBound="1" eType="//EClass" eOpposite="//EClass/eStructuralFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeable" ordered="false" lowerBound="1" defaultValueLiteral="true">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EJavaObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueLiteral" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unsettable" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volatile" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EInt" instanceClassName="int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EIntegerObject" instanceClassName="java.lang.Integer"/>
  <eClassifiers xsi:type="ecore:EClass" name="EPackage" eSuperTypes="//ENamedElement">
    <eOperations name="getEClassifier" eType="//EClassifier">
      <eParameters name="name">
        <eType xsi:type="ecore:EDataType" href="#//EString"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifiers" upperBound="-1" eType="//EClassifier" containment="true" eOpposite="//EClassifier/ePackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFactoryInstance" lowerBound="1" eType="//EFactory" eOpposite="//EFactory/ePackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eSubpackages" upperBound="-1" eType="//EPackage" containment="true" eOpposite="//EPackage/eSuperPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eSuperPackage" eType="//EPackage" eOpposite="//EPackage/eSubpackages"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsPrefix" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsURI" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EChar" instanceClassName="char"/>
  <eClassifiers xsi:type="ecore:EClass" name="EReference" eSuperTypes="//EStructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReferenceType" lowerBound="1" eType="//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eOpposite" eType="//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="container" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolveProxies" ordered="false" lowerBound="1" defaultValueLiteral="true">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBigInteger" instanceClassName="java.math.BigInteger"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDataType" eSuperTypes="//EClassifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serializable" ordered="false" lowerBound="1" defaultValueLiteral="true">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EJavaClass" instanceClassName="java.lang.Class"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EJavaObject" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EBigDecimal" instanceClassName="java.math.BigDecimal"/>
  <eClassifiers xsi:type="ecore:EClass" name="EEnumLiteral" eSuperTypes="//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eEnum" lowerBound="1" eType="//EEnum" eOpposite="//EEnum/eLiterals"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance" ordered="false" lowerBound="1" eType="//EEnumerator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EEList&lt;E>" instanceClassName="org.eclipse.emf.common.util.EList"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EBooleanObject" instanceTypeName="Boolean"/>
  <eClassifiers xsi:type="ecore:EClass" name="EAnnotation" eSuperTypes="//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eModelElement" lowerBound="1" eType="//EModelElement" eOpposite="//EModelElement/eAnnotations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1" eType="//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1" eType="//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="details" ordered="false" lowerBound="1" eType="//EStringToStringMapEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass" eSuperTypes="//EClassifier">
    <eOperations name="getEStructuralFeature" eType="//EStructuralFeature">
      <eParameters name="featureID">
        <eType xsi:type="ecore:EDataType" href="#//EInt"/>
      </eParameters>
    </eOperations>
    <eOperations name="getEStructuralFeature" eType="//EStructuralFeature">
      <eParameters name="featureName" eType="//EString"/>
    </eOperations>
    <eOperations name="isSuperTypeOf" eType="//EBoolean">
      <eParameters name="someClass">
        <eType xsi:type="ecore:EClass" href="#//EClass"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eOperations" upperBound="-1" eType="//EOperation" containment="true" eOpposite="//EOperation/eContainingClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eIDAttribute" eType="//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributes" upperBound="-1" eType="//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllGenericSuperTypes" upperBound="-1" eType="//EGenericType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eSuperTypes" upperBound="-1" eType="//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllSuperTypes" upperBound="-1" eType="//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllOperations" upperBound="-1" eType="//EOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllAttributes" upperBound="-1" eType="//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericSuperTypes" upperBound="-1" eType="//EGenericType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllReferences" upperBound="-1" eType="//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eReferences" upperBound="-1" eType="//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllContainments" upperBound="-1" eType="//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eStructuralFeatures" upperBound="-1" eType="//EStructuralFeature" containment="true" eOpposite="//EStructuralFeature/eContainingClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAllStructuralFeatures" upperBound="-1" eType="//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EMap&lt;K,V>" instanceClassName="java.util.Map"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ECharacterObject" instanceClassName="java.lang.Character"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGenericType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeParameter" eType="//ETypeParameter" eOpposite="//ETypeParameter/eGenericTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifier" eType="//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeArguments" upperBound="-1" eType="//EGenericType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eLowerBound" eType="//EGenericType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eRawType" lowerBound="1" eType="//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eUpperBound" eType="//EGenericType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EByteArray" instanceClassName="byte[]"/>
  <eClassifiers xsi:type="ecore:EClass" name="EAttribute" eSuperTypes="//EStructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributeType" lowerBound="1" eType="//EDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringToStringMapEntry" instanceClassName="java.util.Map$Entry" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EByteObject" instanceClassName="java.lang.Byte"/>
  <eClassifiers xsi:type="ecore:EClass" name="EFactory" eSuperTypes="//EModelElement">
    <eOperations name="convertToString">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
      <eParameters name="eDataType">
        <eType xsi:type="ecore:EClass" href="#//EDataType"/>
      </eParameters>
      <eParameters name="instanceValue">
        <eType xsi:type="ecore:EDataType" href="#//EJavaObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="create" eType="//EObject">
      <eParameters name="eClass">
        <eType xsi:type="ecore:EClass" href="#//EClass"/>
      </eParameters>
    </eOperations>
    <eOperations name="createFromString">
      <eType xsi:type="ecore:EDataType" href="#//EJavaObject"/>
      <eParameters name="eDataType">
        <eType xsi:type="ecore:EClass" href="#//EDataType"/>
      </eParameters>
      <eParameters name="literalValue">
        <eType xsi:type="ecore:EDataType" href="#//EString"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" lowerBound="1" eType="//EPackage" eOpposite="//EPackage/eFactoryInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EShortObject" instanceClassName="java.lang.Short"/>
  <eClassifiers xsi:type="ecore:EClass" name="ETypeParameter" eSuperTypes="//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericTypes" upperBound="-1" eType="//EGenericType" eOpposite="//EGenericType/eTypeParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBounds" upperBound="-1" eType="//EGenericType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ELongObject" instanceClassName="java.lang.Long"/>
  <eClassifiers xsi:type="ecore:EClass" name="EModelElement" abstract="true" eSuperTypes="//EObject">
    <eOperations name="getEAnnotation" eType="//EAnnotation">
      <eParameters name="source">
        <eType xsi:type="ecore:EDataType" href="#//EString"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eAnnotations" upperBound="-1" eType="//EAnnotation" containment="true" eOpposite="//EAnnotation/eModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBoolean" instanceClassName="boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFloat" instanceClassName="float"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFloatObject" instanceClassName="java.lang.Float"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EString" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EResource" instanceClassName="org.eclipse.emf.ecore.resource.Resource"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EByte" instanceClassName="byte"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureMap" instanceClassName="org.eclipse.emf.ecore.util.FeatureMap"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClassifier" abstract="true" eSuperTypes="//ENamedElement">
    <eOperations name="getClassifierID">
      <eType xsi:type="ecore:EDataType" href="#//EInt"/>
    </eOperations>
    <eOperations name="isInstance">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
      <eParameters name="object">
        <eType xsi:type="ecore:EDataType" href="#//EJavaObject"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeParameters" upperBound="-1" eType="//ETypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" lowerBound="1" eType="//EPackage" eOpposite="//EPackage/eClassifiers"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EJavaObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceClass" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EJavaClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceClassName" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceTypeName" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EDate" instanceClassName="java.util.Date"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EEnumerator" instanceClassName="org.eclipse.emf.common.util.Enumerator"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EDiagnosticChain" instanceClassName="org.eclipse.emf.common.util.DiagnosticChain"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ETreeIterator" instanceClassName="org.eclipse.emf.common.util.TreeIterator"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFeatureMapEntry" instanceClassName="org.eclipse.emf.ecore.util.FeatureMap$Entry"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENamedElement" abstract="true" eSuperTypes="//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ELong" instanceClassName="long"/>
  <eClassifiers xsi:type="ecore:EClass" name="EObject">
    <eOperations name="eAllContents" eType="//ETreeIterator"/>
    <eOperations name="eClass" eType="//EClass"/>
    <eOperations name="eContainer" eType="//EObject"/>
    <eOperations name="eContainingFeature" eType="//EStructuralFeature"/>
    <eOperations name="eContainmentFeature" eType="//EReference"/>
    <eOperations name="eContents" eType="//EEList%3CE%3E"/>
    <eOperations name="eCrossReferences" eType="//EEList%3CE%3E"/>
    <eOperations name="eGet" eType="//EJavaObject">
      <eParameters name="feature" eType="//EStructuralFeature"/>
    </eOperations>
    <eOperations name="eGet" eType="//EJavaObject">
      <eParameters name="resolve">
        <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
      </eParameters>
      <eParameters name="feature" eType="//EStructuralFeature"/>
    </eOperations>
    <eOperations name="eInvoke" eType="//EJavaObject">
      <eParameters name="operation" eType="//EOperation"/>
      <eParameters name="arguments" eType="//EEList%3CE%3E"/>
    </eOperations>
    <eOperations name="eIsProxy">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eOperations>
    <eOperations name="eIsSet">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
      <eParameters name="feature" eType="//EStructuralFeature"/>
    </eOperations>
    <eOperations name="eResource">
      <eType xsi:type="ecore:EDataType" href="#//EResource"/>
    </eOperations>
    <eOperations name="eSet">
      <eParameters name="newValue" eType="//EJavaObject"/>
      <eParameters name="feature" eType="//EStructuralFeature"/>
    </eOperations>
    <eOperations name="eUnset">
      <eParameters name="feature" eType="//EStructuralFeature"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EResourceSet" instanceClassName="org.eclipse.emf.ecore.resource.ResourceSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="EEnum" eSuperTypes="//EDataType">
    <eOperations name="getEEnumLiteral" eType="//EEnumLiteral">
      <eParameters name="name">
        <eType xsi:type="ecore:EDataType" href="#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="getEEnumLiteral" eType="//EEnumLiteral">
      <eParameters name="value">
        <eType xsi:type="ecore:EDataType" href="#//EInt"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eLiterals" upperBound="-1" eType="//EEnumLiteral" containment="true" eOpposite="//EEnumLiteral/eEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EShort" instanceClassName="short"/>
  <eClassifiers xsi:type="ecore:EClass" name="EOperation" eSuperTypes="//ETypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eParameters" upperBound="-1" eType="//EParameter" containment="true" eOpposite="//EParameter/eOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eExceptions" upperBound="-1" eType="//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eTypeParameters" upperBound="-1" eType="//ETypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericExceptions" upperBound="-1" eType="//EGenericType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eContainingClass" lowerBound="1" eType="//EClass" eOpposite="//EClass/eOperations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EDouble" instanceClassName="double"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDoubleObject" instanceClassName="java.lang.Double" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EParameter" eSuperTypes="//ETypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eOperation" lowerBound="1" eType="//EOperation" eOpposite="//EOperation/eParameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ETypedElement" abstract="true" eSuperTypes="//ENamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGenericType" eType="//EGenericType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" ordered="false" lowerBound="1" defaultValueLiteral="true">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" ordered="false" lowerBound="1" defaultValueLiteral="true">
      <eType xsi:type="ecore:EDataType" href="#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" ordered="false" lowerBound="1" defaultValueLiteral="1">
      <eType xsi:type="ecore:EDataType" href="#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
