<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Moca" nsURI="http://www.moflon.org.Moca" nsPrefix="Moca">
  <eClassifiers xsi:type="ecore:EClass" name="CodeAdapter">
    <eOperations name="parse">
      <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Folder"/>
      <eParameters name="dir" eType="//Directory"/>
    </eOperations>
    <eOperations name="unparse" eType="//Directory">
      <eParameters name="path">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
      <eParameters name="folder">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Folder"/>
      </eParameters>
    </eOperations>
    <eOperations name="parseFile">
      <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//File"/>
      <eParameters name="file" eType="//Directory"/>
      <eParameters name="parent">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Folder"/>
      </eParameters>
    </eOperations>
    <eOperations name="unparseFile">
      <eParameters name="eFile">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//File"/>
      </eParameters>
      <eParameters name="dir" eType="//Directory"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unparser" upperBound="-1" eType="//unparser/Unparser" containment="true" eOpposite="//unparser/Unparser/codeAdapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="problems" upperBound="-1" eType="//Problem" containment="true" eOpposite="//Problem/codeAdapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parser" upperBound="-1" eType="//parser/Parser" containment="true" eOpposite="//parser/Parser/codeAdapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Reader" instanceClassName="java.io.Reader"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Directory" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ProblemType">
    <eLiterals name="ERROR"/>
    <eLiterals name="WARNING" value="1"/>
    <eLiterals name="INFO" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Problem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeAdapter" lowerBound="1" eType="//CodeAdapter" eOpposite="//CodeAdapter/problems"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" eType="//ProblemType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterPositionEnd" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterPositionStart" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="compare" nsURI="http://www.moflon.org.Moca.compare" nsPrefix="compare">
    <eClassifiers xsi:type="ecore:EClass" name="MocaCompare">
      <eOperations name="cacheRightFolder">
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Folder"/>
        </eParameters>
      </eOperations>
      <eOperations name="collectAddition">
        <eParameters name="element">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//TreeElement"/>
        </eParameters>
        <eParameters name="leftParent">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//TreeElement"/>
        </eParameters>
      </eOperations>
      <eOperations name="collectDeletion">
        <eParameters name="element">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//TreeElement"/>
        </eParameters>
        <eParameters name="leftParent">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//TreeElement"/>
        </eParameters>
      </eOperations>
      <eOperations name="compare">
        <eParameters name="left">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Folder"/>
        </eParameters>
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Folder"/>
        </eParameters>
      </eOperations>
      <eOperations name="compareFile">
        <eParameters name="left">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//File"/>
        </eParameters>
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//File"/>
        </eParameters>
      </eOperations>
      <eOperations name="compareFolder">
        <eParameters name="left">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Folder"/>
        </eParameters>
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Folder"/>
        </eParameters>
      </eOperations>
      <eOperations name="compareNode">
        <eParameters name="left">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
        </eParameters>
        <eParameters name="right">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
        </eParameters>
      </eOperations>
      <eOperations name="getTreeElement">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//TreeElement"/>
        <eParameters name="parent">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//TreeElement"/>
        </eParameters>
        <eParameters name="name">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
        <eParameters name="index">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addition" upperBound="-1" eType="//compare/Addition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deletion" upperBound="-1" eType="//compare/Deletion" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="foundRightRlements" upperBound="-1">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//TreeElement"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Deletion" eSuperTypes="//compare/MocaDiff"/>
    <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="//compare/MocaDiff"/>
    <eClassifiers xsi:type="ecore:EClass" name="MocaDiff" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//TreeElement"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftParent">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//TreeElement"/>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="parser" nsURI="http://www.moflon.org.Moca.parser" nsPrefix="parser">
    <eClassifiers xsi:type="ecore:EClass" name="Parser" abstract="true">
      <eOperations name="canParseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eOperations name="parse">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
        <eParameters name="reader" eType="//Reader"/>
      </eOperations>
      <eOperations name="parse">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
        <eParameters name="file" eType="//File"/>
        <eParameters name="reader" eType="//Reader"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codeAdapter" lowerBound="1" eType="//CodeAdapter" eOpposite="//CodeAdapter/parser"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMLParser" eSuperTypes="//parser/Parser">
      <eOperations name="canParseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eOperations name="parse">
        <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
        <eParameters name="reader" eType="//Reader"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreWhitespaces" ordered="false" lowerBound="1" defaultValueLiteral="true">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="unparser" nsURI="http://www.moflon.org.Moca.unparser" nsPrefix="unparser">
    <eClassifiers xsi:type="ecore:EClass" name="XMLUnparser" abstract="true" eSuperTypes="//unparser/TemplateUnparser">
      <eOperations name="canUnparseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eOperations name="unparse">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="node">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateUnparser" abstract="true" eSuperTypes="//unparser/Unparser">
      <eOperations name="canUnparseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eOperations name="unparse">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="node">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unparser" abstract="true">
      <eOperations name="unparse">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="node">
          <eType xsi:type="ecore:EClass" href="http://www.moflon.org.MocaTree#//Node"/>
        </eParameters>
      </eOperations>
      <eOperations name="canUnparseFile">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="fileName">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codeAdapter" lowerBound="1" eType="//CodeAdapter" eOpposite="//CodeAdapter/unparser"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
