<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SDMLanguage" nsURI="http://www.moflon.org.SDMLanguage" nsPrefix="SDMLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="CommentableElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="activities" nsURI="http://www.moflon.org.SDMLanguage.activities" nsPrefix="activities">
    <eClassifiers xsi:type="ecore:EClass" name="StopNode" eSuperTypes="//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" eType="//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivity" lowerBound="1" eType="//activities/Activity" eOpposite="//activities/Activity/ownedActivityEdge"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//activities/ActivityNode" eOpposite="//activities/ActivityNode/outgoing"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//activities/ActivityNode" eOpposite="//activities/ActivityNode/incoming"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" ordered="false" lowerBound="1" eType="//activities/EdgeGuard" defaultValueLiteral="EdgeGuard.NONE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoryNode" eSuperTypes="//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="storyPattern" lowerBound="1" eType="//patterns/StoryPattern" containment="true" eOpposite="//patterns/StoryPattern/storyNode"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="forEach" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StatementNode" eSuperTypes="//activities/ActivityNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statementExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StartNode" eSuperTypes="//activities/ActivityNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="//NamedElement //CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivity" lowerBound="1" eType="//activities/Activity" eOpposite="//activities/Activity/ownedActivityNode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1" eType="//activities/ActivityEdge" eOpposite="//activities/ActivityEdge/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1" eType="//activities/ActivityEdge" eOpposite="//activities/ActivityEdge/target"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EdgeGuard">
      <eLiterals name="NONE"/>
      <eLiterals name="SUCCESS" value="1"/>
      <eLiterals name="FAILURE" value="2"/>
      <eLiterals name="EACH_TIME" value="3"/>
      <eLiterals name="END" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityNode" upperBound="-1" eType="//activities/ActivityNode" containment="true" eOpposite="//activities/ActivityNode/owningActivity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityEdge" upperBound="-1" eType="//activities/ActivityEdge" containment="true" eOpposite="//activities/ActivityEdge/owningActivity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningOperation">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MoflonEOperation">
      <eSuperTypes href="http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="//activities/Activity" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="precompiler" nsURI="http://www.moflon.org.SDMLanguage.precompiler" nsPrefix="precompiler">
    <eClassifiers xsi:type="ecore:EClass" name="SDMPrecompiler">
      <eOperations name="processActivity">
        <eParameters name="activity" eType="//activities/Activity"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="calls" nsURI="http://www.moflon.org.SDMLanguage.calls" nsPrefix="calls">
    <eClassifiers xsi:type="ecore:EClass" name="Invocation" abstract="true" eSuperTypes="//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameterBindings" upperBound="-1" eType="//calls/ParameterBinding" containment="true" eOpposite="//calls/ParameterBinding/invocation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="callee" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterBinding" eSuperTypes="//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocation" lowerBound="1" eType="//calls/Invocation" eOpposite="//calls/Invocation/ownedParameterBindings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EParameter"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eSubpackages name="callExpressions" nsURI="http://www.moflon.org.SDMLanguage.calls.callExpressions" nsPrefix="callExpressions">
      <eClassifiers xsi:type="ecore:EClass" name="ParameterExpression" eSuperTypes="//expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1">
          <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EParameter"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MethodCallExpression" eSuperTypes="//expressions/Expression //calls/Invocation">
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="http://www.moflon.org.SDMLanguage.expressions" nsPrefix="expressions">
    <eClassifiers xsi:type="ecore:EClass" name="TextualExpression" eSuperTypes="//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionText" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageVersion" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="//CommentableElement">
      <eOperations name="compare">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eParameters name="expression" eType="//expressions/Expression"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true" eSuperTypes="//expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="//expressions/Expression //TypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" lowerBound="1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" eSuperTypes="//expressions/BinaryExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false" lowerBound="1" eType="//expressions/ComparingOperator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ComparingOperator">
      <eLiterals name="LESS"/>
      <eLiterals name="LESS_OR_EQUAL" value="1"/>
      <eLiterals name="EQUAL" value="2"/>
      <eLiterals name="GREATER_OR_EQUAL" value="3"/>
      <eLiterals name="GREATER" value="4"/>
      <eLiterals name="UNEQUAL" value="5"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="patterns" nsURI="http://www.moflon.org.SDMLanguage.patterns" nsPrefix="patterns">
    <eClassifiers xsi:type="ecore:EEnum" name="BindingSemantics">
      <eLiterals name="MANDATORY"/>
      <eLiterals name="OPTIONAL" value="2"/>
      <eLiterals name="NEGATIVE" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoryPattern" eSuperTypes="//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" upperBound="-1" eType="//patterns/ObjectVariable" containment="true" eOpposite="//patterns/ObjectVariable/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkVariable" upperBound="-1" eType="//patterns/LinkVariable" containment="true" eOpposite="//patterns/LinkVariable/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="applicationConditions" upperBound="-1" eType="//patterns/ApplicationConditionStoryPattern" containment="true" eOpposite="//patterns/ApplicationConditionStoryPattern/storyPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeConstraint" containment="true" eOpposite="//patterns/AttributeConstraints/AttributeConstraint/storyPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeConstraintVariable" containment="true" eOpposite="//patterns/AttributeConstraints/AttributeConstraintVariable/storyPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="storyNode" lowerBound="1" eType="//activities/StoryNode" eOpposite="//activities/StoryNode/storyPattern"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeAssignment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" lowerBound="1" eType="//patterns/ObjectVariable" eOpposite="//patterns/ObjectVariable/attributeAssignment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectVariable" eSuperTypes="//TypedElement //NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1" eType="//patterns/Constraint" containment="true" eOpposite="//patterns/Constraint/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLink" upperBound="-1" eType="//patterns/LinkVariable" eOpposite="//patterns/LinkVariable/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLink" upperBound="-1" eType="//patterns/LinkVariable" eOpposite="//patterns/LinkVariable/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeAssignment" upperBound="-1" eType="//patterns/AttributeAssignment" containment="true" eOpposite="//patterns/AttributeAssignment/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingOperator" ordered="false" lowerBound="1" eType="//patterns/BindingOperator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingSemantics" ordered="false" lowerBound="1" eType="//patterns/BindingSemantics"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingState" ordered="false" lowerBound="1" eType="//patterns/BindingState"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkVariable" eSuperTypes="//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="//patterns/ObjectVariable" eOpposite="//patterns/ObjectVariable/incomingLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="//patterns/ObjectVariable" eOpposite="//patterns/ObjectVariable/outgoingLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/linkVariable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingOperator" ordered="false" lowerBound="1" eType="//patterns/BindingOperator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingSemantics" ordered="false" lowerBound="1" eType="//patterns/BindingSemantics"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BindingOperator">
      <eLiterals name="CHECK_ONLY"/>
      <eLiterals name="CREATE" value="1"/>
      <eLiterals name="DESTROY" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BindingState">
      <eLiterals name="UNBOUND"/>
      <eLiterals name="BOUND" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ApplicationConditionStoryPattern" eSuperTypes="//patterns/StoryPattern">
      <eStructuralFeatures xsi:type="ecore:EReference" name="storyPattern" lowerBound="1" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/applicationConditions"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraintExpression" lowerBound="1" eType="//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" lowerBound="1" eType="//patterns/ObjectVariable" eOpposite="//patterns/ObjectVariable/constraint"/>
    </eClassifiers>
    <eSubpackages name="AttributeConstraints" nsURI="http://www.moflon.org.SDMLanguage.patterns.AttributeConstraints" nsPrefix="AttributeConstraints">
      <eClassifiers xsi:type="ecore:EClass" name="CspConstraint" eSuperTypes="//patterns/AttributeConstraints/AttributeConstraint">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeConstraintVariable" eOpposite="//patterns/AttributeConstraints/AttributeConstraintVariable/cspConstraints"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PrimitiveVariable" eSuperTypes="//patterns/AttributeConstraints/AttributeConstraintVariable"/>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraintExpression" eSuperTypes="//expressions/Expression">
        <eOperations name="compare">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
          <eParameters name="expression" eType="//expressions/Expression"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="targetVariable" lowerBound="1" eType="//patterns/AttributeConstraints/AttributeConstraintVariable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="containedVariables" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeConstraintVariable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="containedConstraints" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeConstraint" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraintVariable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="cspConstraints" upperBound="-1" eType="//patterns/AttributeConstraints/CspConstraint" eOpposite="//patterns/AttributeConstraints/CspConstraint/parameters"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="storyPattern" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/variables"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="attributeValueConstraints" upperBound="-1" eType="//patterns/AttributeConstraints/AttributeValueConstraint" eOpposite="//patterns/AttributeConstraints/AttributeValueConstraint/parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type">
          <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LiteralVariable" eSuperTypes="//patterns/AttributeConstraints/AttributeConstraintVariable"/>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeValueConstraint" eSuperTypes="//patterns/AttributeConstraints/AttributeConstraint">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="//patterns/AttributeConstraints/AttributeConstraintVariable" eOpposite="//patterns/AttributeConstraints/AttributeConstraintVariable/attributeValueConstraints"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" eType="//patterns/ObjectVariable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type">
          <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeLookupConstraint" eSuperTypes="//patterns/AttributeConstraints/AttributeValueConstraint"/>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraint">
        <eStructuralFeatures xsi:type="ecore:EReference" name="storyPattern" lowerBound="1" eType="//patterns/StoryPattern" eOpposite="//patterns/StoryPattern/constraints"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AssignmentConstraint" eSuperTypes="//patterns/AttributeConstraints/AttributeValueConstraint"/>
    </eSubpackages>
    <eSubpackages name="patternExpressions" nsURI="http://www.moflon.org.SDMLanguage.patterns.patternExpressions" nsPrefix="patternExpressions">
      <eClassifiers xsi:type="ecore:EClass" name="ObjectRefExpression" abstract="true" eSuperTypes="//expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1" eType="//patterns/ObjectVariable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ObjectVariableExpression" eSuperTypes="//patterns/patternExpressions/ObjectRefExpression //expressions/Expression"/>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeValueExpression" eSuperTypes="//patterns/patternExpressions/ObjectRefExpression //expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1">
          <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
