<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TGGRuntime" nsURI="http://www.moflon.org.TGGRuntime" nsPrefix="TGGRuntime">
  <eClassifiers xsi:type="ecore:EClass" name="EquivalenceClasses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="equivalenceclass" upperBound="-1" eType="//EquivalenceClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" upperBound="-1" eType="//Edge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsApplicableRuleResult" eSuperTypes="//RuleResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isApplicableMatch" upperBound="-1" eType="//IsApplicableMatch" containment="true" eOpposite="//IsApplicableMatch/isApplicableRuleResult"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coreMatch" lowerBound="1" eType="//Match"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performOperation" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsApplicableMatch">
    <eOperations name="registerObject">
      <eParameters name="name">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
      <eParameters name="object">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="getObject">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="name">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isApplicableRuleResult" lowerBound="1" eType="//IsApplicableRuleResult" eOpposite="//IsApplicableRuleResult/isApplicableMatch"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeInfo" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleName" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorrespondenceModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondences" upperBound="-1" containment="true">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePrecedenceGraph" eType="//PrecedenceGraph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPrecedenceGraph" eType="//PrecedenceGraph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consistencyTable" lowerBound="1" eType="//ConsistencyTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEdgeTable" lowerBound="1" eType="//EdgeTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEdgeTable" lowerBound="1" eType="//EdgeTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToBeTranslated">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toBeTranslatedEdges" upperBound="-1" eType="//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toBeTranslatedNodes" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="success" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rule" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsistencyTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1" eType="//ConsistencyEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsistencyEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEdges" upperBound="-1" eType="//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEdges" upperBound="-1" eType="//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetNodes" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceNodes" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondenceNodes" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalenceClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" upperBound="-1" eType="//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="succeeding" upperBound="-1" eType="//EquivalenceClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eobject" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrecedenceGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="equivalenceclass" upperBound="-1" eType="//EquivalenceClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformRuleResult" eSuperTypes="//RuleResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdEdges" upperBound="-1" eType="//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="translatedEdges" upperBound="-1" eType="//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="translatedElements" lowerBound="1" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdElements" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdLinkElements" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCorrespondence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Match">
    <eOperations name="computeHash">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getObject">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="name">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations name="registerObject">
      <eParameters name="name">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
      <eParameters name="object">
        <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="setMatchContent" eType="//Match">
      <eParameters name="match" eType="//Match"/>
    </eOperations>
    <eOperations name="setNameToObjectRegistration">
      <eParameters name="match" eType="//Match"/>
    </eOperations>
    <eOperations name="size">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextEdges" upperBound="-1" eType="//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toBeTranslatedEdges" upperBound="-1" eType="//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeRuleInvocations" upperBound="-1" eType="//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isApplicableOperation">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toBeTranslatedElements" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextNodes" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleName" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
