<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="soccerpitch" nsURI="http://www.transformation-tool-contest.eu/soccerpitch/1.0" nsPrefix="soccerpitch">
  <eClassifiers xsi:type="ecore:EClass" name="Ball">
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" eType="//Player" eOpposite="//Player/ball"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="//Field" eOpposite="//Field/ball"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoccerPitch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1" eType="//Player" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1" eType="//Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ball" lowerBound="1" eType="//Ball" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownTeam" ordered="false" lowerBound="1" eType="//Teams"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opponentTeam" ordered="false" lowerBound="1" eType="//Teams"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1" eType="//Player" eOpposite="//Player/field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ball" eType="//Ball" eOpposite="//Ball/field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="south" eType="//Field" eOpposite="//Field/north"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="north" eType="//Field" eOpposite="//Field/south"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="west" eType="//Field" eOpposite="//Field/east"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="east" eType="//Field" eOpposite="//Field/west"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPos" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yPos" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalField" eSuperTypes="//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="team" ordered="false" lowerBound="1" eType="//Teams" defaultValueLiteral="BLUE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Teams">
    <eLiterals name="RED" value="1"/>
    <eLiterals name="BLUE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="//Field" eOpposite="//Field/players"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ball" eType="//Ball" eOpposite="//Ball/player"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" ordered="false" lowerBound="1" defaultValueLiteral="0">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="team" ordered="false" lowerBound="1" eType="//Teams" defaultValueLiteral="BLUE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalKeeper" eSuperTypes="//Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="FieldPlayer" eSuperTypes="//Player"/>
</ecore:EPackage>
